### ISSUE TITLE
[Icon request] WASM

### ISSUE THREAD

**Issue by itsezc** [tabler/tabler-icons#601] opened 2023-04-05 09:37 UTC
WebAssembly is an emerging web standard, and a lot of apps are already running on it.

![image](https://user-images.githubusercontent.com/33750251/230042637-d4738e48-82e8-4b80-9ea4-0dc036e4bca1.png)

**Comment by 0xflotus** [comment] 2023-04-10 11:11
Duplicate of #438

**Closed** 2023-04-10 19:46 UTC
