### ISSUE TITLE
[Icon request] Rust

### ISSUE THREAD

**Issue by itsezc** [tabler/tabler-icons#592] opened 2023-04-05 08:27 UTC
The rust programming language as an icon:

![image](https://user-images.githubusercontent.com/33750251/230025429-2bb32751-0b4e-4aa4-b1bd-cbf3342cf873.png)

**Comment by Narcha** [comment] 2023-04-07 07:36
Duplicate of #437

**Closed** 2023-04-07 12:08 UTC
