### ISSUE TITLE
Deploy @tabler/icons-svelte with "Could not resolve" error

### ISSUE THREAD

**Issue by fanshuai** [tabler/tabler-icons#838] opened 2023-09-17 23:26 UTC
- Deploy environment: GitHub Actions
- Try package version: "@tabler/icons": "2.34.0"、"2.32.0"
- Deploy build command: npm, "vite build"
- Error message: `Could not resolve "./icons/IconDeviceGamepad.svelte" from "node_modules/@tabler/icons-svelte/dist/svelte/tabler-icons-svelte.js"`

<img width="1137" alt="image" src="https://github.com/tabler/tabler-icons/assets/1005487/3e7f47cd-db3e-48bb-98c5-07638ef0a72e">

- The version "@tabler/icons": "2.31.0" is OK, so it seems like a problem starting from version "2.32.0".

**Comment by hanszoons** [comment] 2023-09-19 08:19
Dupe of #810

**Comment by codecalm** [comment] 2023-09-27 22:02
fixed 🙂

**Closed by codecalm** 2023-09-27 22:02 UTC
