### ISSUE TITLE
[Icon request] Passkey

### ISSUE THREAD

**Issue by fanshuai** [tabler/tabler-icons#896] opened 2023-11-04 01:29 UTC
A passkey is a digital credential that is used as an authentication method for a website or application. The passkeys standard is a type of passwordless authentication, promoted by the World Wide Web Consortium and the FIDO Alliance. They are often stored by the operating system or web browser and synchronized between devices from the same ecosystem using the cloud, however they can also be confined to a single device such as a physical security key
-- Quote Wikipedia

- https://en.wikipedia.org/wiki/Passkey_(authentication)
- https://developer.apple.com/passkeys/
- https://developer.android.com/training/sign-in/passkeys

Thanks!

**Comment by itsezc** [comment] 2023-12-09 05:37
Duplicate of #607

**Closed** 2023-12-10 10:22 UTC
Labels: icon request, dupliacte
