### ISSUE TITLE
Duplicate Icon: message-circle

### ISSUE THREAD

**Issue by ShahriarKh** [tabler/tabler-icons#965] opened 2024-01-01 08:41 UTC
`message-circle` and `message-circle-2` look identical. Maybe keep one of them only?
https://tabler.io/icons/icon/message-circle
https://tabler.io/icons/icon/message-circle-2

**Comment by BG-Software-BG** [comment] 2024-01-01 15:54
Duplicate of #743

**Closed by BG-Software-BG** 2024-01-01 15:54 UTC
Labels: bug, dupliacte
