### ISSUE TITLE
[Icon Request] country or continent icon

### ISSUE THREAD

**Issue by sebastienbarre** [tabler/tabler-icons#1113] opened 2024-05-03 15:27 UTC
Would be great to have something that represents a country. 
Now there are far too many countries to make one icon per country, but maybe one icon for the Americas, and one for Europe, and maybe one for Asia? More like continent icons, which could be used to symbolize a country too.

Thank you

Here are some search examples I found:

<img width="1484" alt="image" src="https://github.com/tabler/tabler-icons/assets/329967/88cf4d56-aad2-47ca-9939-ee51f19ccd09">

**Comment by BG-Software-BG** [comment] 2024-05-05 16:20
It's a duplicate of https://github.com/tabler/tabler-icons/issues/814.

However, those may be very hard to create as a 24x24 px icon.

**Closed by BG-Software-BG** 2024-05-05 16:20 UTC
Labels: icon request, dupliacte

**Comment by sebastienbarre** [comment] 2024-05-05 16:40
Ooops yes, sorry about the duplicate. https://github.com/tabler/tabler-icons/issues/461 is pretty close to what I would like, so I'll be following it instead.
