### ISSUE TITLE
[Icon Request] Keyboard (piano) and instruments

### ISSUE THREAD

**Issue by neutralshady** [tabler/tabler-icons#661] opened 2023-05-15 16:54 UTC

**Comment by PeterTYLiu** [comment] 2023-05-19 23:35
Duplicate of #215

**Comment by codecalm** [comment] 2023-06-07 17:14
keyboard added in https://github.com/tabler/tabler-icons/releases/tag/v2.22.0 🙂

**Closed by codecalm** 2023-06-07 17:14 UTC
