### ISSUE TITLE
Icon not considered as JSX element in SolidJS

### ISSUE THREAD

**Issue by lockieluke** [tabler/tabler-icons#1062] opened 2024-03-15 23:21 UTC
![image](https://github.com/tabler/tabler-icons/assets/25424409/423fcd0c-c899-467a-9ebe-9895a6b1dc48)

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": [
      "ES2020",
      "DOM",
      "DOM.Iterable"
    ],
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "jsxImportSource": "solid-js",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "paths": {
      "@src/*": [
        "./src/*"
      ],
      "@assets/*": [
        "./src/assets/*"
      ]
    }
  },
  "include": [
    "src"
  ],
  "references": [
    {
      "path": "./tsconfig.node.json"
    }
  ]
}
```

**Comment by chenkovsky** [comment] 2024-03-17 08:38
I think you should try  https://github.com/jfgodoy/vite-plugin-solid-svg

**Comment by chenkovsky** [comment] 2024-03-17 08:52
I tried old version. it works

**Comment by BG-Software-BG** [comment] 2024-03-17 10:53
Duplicate of #1060

**Comment by lockieluke** [comment] 2024-03-17 10:58
what am I doing wrong then

**Comment by lockieluke** [comment] 2024-03-17 17:18
can confirm downgrading to `2.47.0` works

**Comment by daalfox** [comment] 2024-04-13 11:05
Any update on this?

**Comment by dmaximyuk** [comment] 2024-05-13 06:53
Confirm. I'm catching the same mistake. Is there a solution other than any?

**Comment by pedrodesu** [comment] 2024-06-10 01:53
bump

**Comment by pedrodesu** [comment] 2024-06-26 22:03
as of v3.7.0 this issue seems solved.

**Closed** 2024-06-27 05:15 UTC
Labels: bug, important, dupliacte
