### ISSUE TITLE
[Icon Request] Brand DuckDuckGo 

### ISSUE THREAD

**Issue by john-mantas** [tabler/tabler-icons#837] opened 2023-09-17 18:21 UTC
A brand icon for the search engine DuckDuckGo, they have a colorful version in their [press material](https://duckduckgo.com/press). Thank you in advance.

**Comment by BG-Software-BG** [comment] 2023-12-08 21:42
Duplicate of #740

**Closed by BG-Software-BG** 2023-12-08 21:42 UTC
Labels: icon request, dupliacte
