### ISSUE TITLE
Unnecessary top padding to icons

### ISSUE THREAD

**Issue by yahu1031** [tabler/tabler-icons#139] opened 2021-05-15 07:47 UTC
I'm using this font directly into flutter with IconData something like this
```dart
const IconData home = IconData(0xeac1, fontFamily: 'IconsFont');
```
And when I use, I get un necessary top padding to the data for no reason.
![Tabler-icon](https://user-images.githubusercontent.com/35523357/118352244-fd4aa880-b57d-11eb-87c6-d775e50b79e6.png)
The home image must be in the middle of the blue container. But the wasn't.
When i tried copy pasting the icon svg code figma I found it has perfect padding. But what about this in flutter i don't understand and other icons just work pretty fine
![Material-icon](https://user-images.githubusercontent.com/35523357/118352343-9a0d4600-b57e-11eb-8ddc-9cf00f59fa54.png)
I can prefer you no to have any padding like this
```svg
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M3 10H1L10 1L19 10H17" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M3 10V17C3 17.5304 3.21071 18.0391 3.58579 18.4142C3.96086 18.7893 4.46957 19 5 19H15C15.5304 19 16.0391 18.7893 16.4142 18.4142C16.7893 18.0391 17 17.5304 17 17V10" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M7 19V13C7 12.4696 7.21071 11.9609 7.58579 11.5858C7.96086 11.2107 8.46957 11 9 11H11C11.5304 11 12.0391 11.2107 12.4142 11.5858C12.7893 11.9609 13 12.4696 13 13V19" stroke="black" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
```

**Comment by Chaphasilor** [comment] 2021-05-16 10:19
duplicate of #118 :)

**Closed** 2023-03-11 12:43 UTC
Labels: bug
