### ISSUE TITLE
Cannot use in production n SvelteKit / Vercel : fails during build

### ISSUE THREAD

**Issue by MarArMar** [tabler/tabler-icons#826] opened 2023-09-10 15:50 UTC
I get this error during a Sveltekit build on Vercel (local build runs fine)

Note : I do NOT use the IconDeviceGamepad anywhere in my app.

build: error during build:
build: RollupError: Could not resolve "./icons/IconDeviceGamepad.svelte" from "../../node_modules/.pnpm/@tabler+icons-svelte@2.34.0_svelte@3.59.1/node_modules/@tabler/icons-svelte/dist/svelte/tabler-icons-svelte.js"
build:     at error (file:///vercel/path0/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:2124:30)
build:     at ModuleLoader.handleInvalidResolvedId (file:///vercel/path0/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:23990:24)
build:     at file:///vercel/path0/node_modules/.pnpm/rollup@3.23.0/node_modules/rollup/dist/es/shared/node-entry.js:23952:26
build:  ELIFECYCLE  Command failed with exit code 1.
build: ERROR: command finished with error: command (/vercel/path0/apps) pnpm run build exited (1)
command (/vercel/path0/apps) pnpm run build exited (1)

**Comment by Clarkden** [comment] 2023-09-12 06:37
I've been getting this issue as well for the past day. I didn't have it before. I recently upgraded the version.

**Comment by neriamosgionata** [comment] 2023-09-12 10:30
Reverting to 2.31 fixes the problem on Linux.
On MacOS this error doesn't occur even with >2.32.

I checked in the node_modules dir, on Linux there is no IconDeviceGamepad.svelte.

**Comment by hanszoons** [comment] 2023-09-19 08:19
Dupe of #810

**Comment by codecalm** [comment] 2023-09-27 22:02
fixed 🙂

**Closed by codecalm** 2023-09-27 22:02 UTC

**Comment by MarArMar** [comment] 2023-09-30 05:03
great, you rock @codecalm !
