### ISSUE TITLE
@tabler/icons-svelte, individual import of icons, dead code elimination, typescript error

### ISSUE THREAD

**Issue by ttmx** [tabler/tabler-icons#938] opened 2023-12-13 13:44 UTC
Hi, since starting to use tabler icons for my svelte project my build times have gone from 2-3 seconds to 40 seconds, this happens because svelte has to bundle all the icons when we import them in the normal way ( `import { IconBattery1} from '@tabler/icons-svelte';`)

I wish to be able to import each Icon individually so that my build times go back to what they were before having to bundle 4000 icons each time.
This is currently doable!
`import IconBattery from '@tabler/icons-svelte/dist/svelte/icons/IconBattery1.svelte';`

The issue here pertains to typescript types: when importing items that way, I get "Could not find a declaration file for module '@tabler/icons-svelte/dist/svelte/icons/IconBattery1.svelte'. '.../app/node_modules/@tabler/icons-svelte/dist/svelte/icons/IconBattery1.svelte' implicitly has an 'any' type."
This could be fixed by also generating a type declaration file for each file.

Is there another way to do this I'm not seeing?

Thank you for the great icons!

**Comment by BG-Software-BG** [comment] 2023-12-14 14:55
Duplicate of #669

**Closed by BG-Software-BG** 2023-12-14 14:55 UTC
Labels: bug, dupliacte
