### ISSUE TITLE
missing exports condition

### ISSUE THREAD

**Issue by miguelgargallo** [tabler/tabler-icons#947] opened 2023-12-16 10:50 UTC
missing exports condition
| If you see a warning logged for this when using a Svelte library, please tell the library maintainers.

Using the svelte field in package.json to point at .svelte source files is deprecated and you must use a svelte [export condition](https://nodejs.org/api/packages.html#conditional-exports). vite-plugin-svelte 3 still resolves it as a fallback, but in a future major release this is going to be removed and without exports condition resolving the library is going to fail.

![missing exports condition](https://github.com/tabler/tabler-icons/assets/5947268/4fa4556b-5528-46b8-837b-284283a0aa51)

**Comment by BG-Software-BG** [comment] 2023-12-17 15:50
Duplicate of #941

**Closed by BG-Software-BG** 2023-12-17 15:50 UTC
Labels: bug, dupliacte
